extends Node

# ALL THIS CODE IS GENERATED BY CLAUDE: https://claude.ai/share/e2b76a14-0255-4a53-a318-0c70000b280b

const BASE_URL = "https://api.openai.com/v1/chat/completions"
const API_KEY = "YOUR_OPENAI_API_KEY_HERE"
const MODEL = "gpt-4o-mini"

var _active_npc: Node = null
# Stores conversation history per agent: { "woody-agent": [...messages] }
var _histories: Dictionary = {}

signal response_received(text: String)

func start_npc_chat(npc: Node) -> void:
	_active_npc = npc
	var agent_name: String = npc.agent_name
	# Start fresh history if first time chatting with this NPC
	if not _histories.has(agent_name):
		_histories[agent_name] = []
	npc.begin_chat()

func send_message(player_input: String) -> void:
	if _active_npc == null:
		print("No active NPC")
		return

	var agent_name: String = _active_npc.agent_name

	# Build context prefix from mood + memory
	var full_input := player_input
	if _active_npc.has_method("get_context_prefix"):
		var prefix: String = _active_npc.get_context_prefix()
		if prefix != "":
			full_input = prefix + player_input

	# Add player message to history
	_histories[agent_name].append({
		"role": "user",
		"content": full_input
	})

	# Build system prompt from NPC data
	var system_prompt := ""
	if _active_npc.has_method("get_system_prompt"):
		system_prompt = _active_npc.get_system_prompt()

	# Assemble messages array
	var messages: Array = []
	if system_prompt != "":
		messages.append({"role": "system", "content": system_prompt})
	messages.append_array(_histories[agent_name])

	var payload = JSON.stringify({
		"model": MODEL,
		"messages": messages,
		"max_tokens": 200
	})

	var req = HTTPRequest.new()
	add_child(req)
	req.request_completed.connect(_on_response.bind(req, player_input, agent_name))
	req.request(BASE_URL,
		["Content-Type: application/json",
		 "Authorization: Bearer " + API_KEY],
		HTTPClient.METHOD_POST, payload)

func _on_response(_result: int, _code: int, _headers: PackedStringArray,
				  body: PackedByteArray, req: HTTPRequest,
				  player_input: String, agent_name: String) -> void:
	var raw := body.get_string_from_utf8()
	var json = JSON.parse_string(raw)
	var npc_text := "..."

	if json is Dictionary and json.has("choices"):
		var choices = json["choices"]
		if choices.size() > 0:
			npc_text = choices[0]["message"]["content"].strip_edges()
			# Add assistant reply to history
			_histories[agent_name].append({
				"role": "assistant",
				"content": npc_text
			})
			# Cap history at 20 messages to avoid token bloat
			if _histories[agent_name].size() > 20:
				_histories[agent_name] = _histories[agent_name].slice(
					_histories[agent_name].size() - 20)
	else:
		print("OpenAI error: ", raw)

	# Store exchange as memory
	if _active_npc != null and _active_npc.has_method("record_memory"):
		_active_npc.record_memory(player_input, npc_text)

	# Suspicion bump
	if _active_npc != null and _active_npc.has_method("increase_suspicion"):
		var keywords := ["ritual", "woods", "night", "symbol", "chanting",
						 "outbuilding", "locked", "cult", "dex", "missing",
						 "apple", "apples", "roundup", "northside", "westpoint"]
		for kw in keywords:
			if player_input.to_lower().contains(kw):
				_active_npc.increase_suspicion(1)
				break

	response_received.emit(npc_text)
	req.queue_free()

func end_npc_chat() -> void:
	if _active_npc and _active_npc.has_method("end_chat"):
		_active_npc.end_chat()
	_active_npc = null
