extends Node

# ALL THIS CODE IS GENERATED BY CLAUDE

const BASE_URL = "http://localhost:8080"

# Tracks one process_id per agent so conversations persist across
# scene changes for the duration of the session
var _process_ids: Dictionary = {}   # { "woody-agent": "abc123", ... }
var _active_agent: String = ""
var _active_npc: Node = null        # typed as Node to avoid circular ref

signal response_received(text: String)

func start_npc_chat(npc: Node) -> void:
	_active_npc = npc
	var agent_name: String = npc.agent_name
	_active_agent = agent_name
	if _process_ids.has(agent_name):
		# Already have a running process for this NPC — reuse it
		npc.begin_chat()
	else:
		# First time chatting with this NPC — create a new process
		_start_conversation(agent_name, npc)
	
func _start_conversation(agent_name: String, npc: Node) -> void:
	var req = HTTPRequest.new()
	add_child(req)
	req.request_completed.connect(_on_process_created.bind(req, agent_name, npc))
	var body = JSON.stringify({"agent": agent_name})
	req.request(BASE_URL + "/processes",
				["Content-Type: application/json"],
				HTTPClient.METHOD_POST, body)

func _on_process_created(_result: int, _code: int, _headers: PackedStringArray, 
						 body: PackedByteArray, req: HTTPRequest,
						 agent_name: String, npc: Node) -> void:
	print("HTTP code: ", _code)
	print("Raw body: ", body.get_string_from_utf8())
	var json = JSON.parse_string(body.get_string_from_utf8())
	if json and json.has("process_id"):
		_process_ids[agent_name] = json["process_id"]
		print("Process created for %s: %s" % [agent_name, json["process_id"]])
		npc.begin_chat()
	else:
		print("Failed to create process for %s: " % agent_name, json)
	req.queue_free()
	
	# ── Send a message ────────────────────────────────────────────────────────────

func send_message(player_input: String) -> void:
	# URL structure matches what the API docs show
	if _active_agent == "" or not _process_ids.has(_active_agent):
		print("No active agent process — did start_npc_chat() complete?")
		return
	var process_id: String = _process_ids[_active_agent]
	var url = "%s/processes/%s/agent/%s/actions/converse" \
			  % [BASE_URL, process_id, _active_agent]

	# Inject context prefix from mood + memory
	var full_message := player_input
	if _active_npc != null and _active_npc.has_method("get_context_prefix"):
		var prefix: String = _active_npc.get_context_prefix()
		if prefix != "":
			full_message = prefix + player_input

	var req = HTTPRequest.new()
	add_child(req)
	req.request_completed.connect(_on_response.bind(req, player_input))
	req.request(url, ["Content-Type: text/plain"],
				HTTPClient.METHOD_POST, full_message)
	
func _on_response(_result: int, _code: int, _headers: PackedStringArray,
				  body: PackedByteArray, req: HTTPRequest,
				  player_input: String) -> void:
	var raw = body.get_string_from_utf8()
	var json = JSON.parse_string(raw)
	var npc_text: String = ""

	if json is Dictionary:
		npc_text = json.get("data", "...")
	else:
		npc_text = raw

	# Store exchange as memory
	if _active_npc != null and _active_npc.has_method("record_memory"):
		_active_npc.record_memory(player_input, npc_text)

	# Suspicion bump if player mentioned a sensitive keyword
	if _active_npc != null and _active_npc.has_method("increase_suspicion"):
		var keywords := ["ritual", "woods", "night", "symbol", "chanting",
						 "outbuilding", "locked", "cult", "dex", "missing",
						 "apple", "apples", "roundup", "northside", "westpoint"]
		for kw in keywords:
			if player_input.to_lower().contains(kw):
				_active_npc.increase_suspicion(1)
				break

	response_received.emit(npc_text)
	req.queue_free()
	
# ── End chat ──────────────────────────────────────────────────────────────────

func end_npc_chat() -> void:
	if _active_npc and _active_npc.has_method("end_chat"):
		_active_npc.end_chat()
	_active_npc = null
	_active_agent = ""
